name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Reconstruction (إعادة الهيكلة)
        run: |
          # حذف المجلدات القديمة المعطوبة
          rm -rf android
          rm -rf ios
          rm -f pubspec.lock
          
          # إجبار فلاتر على إنشاء ملفات نظام أندرويد جديدة وحديثة
          flutter create . --platforms android
          
          # إعادة إضافة المكتبات اللازمة لملف pubspec الجديد
          flutter pub add http url_launcher
          
      - name: Build New APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Tiger-Success-APK
          path: build/app/outputs/flutter-apk/app-release.apk
