name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Recreate Android Files (تجديد النظام)
        run: |
          # حذف ملفات أندرويد القديمة المعطوبة
          rm -rf android
          # إنشاء ملفات أندرويد جديدة تدعم التحديثات
          flutter create . --platforms android
          flutter pub get

      - name: Build Final APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Tiger-Ultimate-Force
          path: build/app/outputs/flutter-apk/app-release.apk
